// Mocks generated by Mockito 5.4.6 from annotations
// in kepleomax/integration_test/mocks/mockito_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kepleomax/core/network/apis/chats/chats_api.dart' as _i3;
import 'package:kepleomax/core/network/apis/chats/chats_dtos.dart' as _i5;
import 'package:kepleomax/core/network/apis/messages/message_dtos.dart' as _i7;
import 'package:kepleomax/core/network/apis/messages/messages_api.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHttpResponse_0<T> extends _i1.SmartFake
    implements _i2.HttpResponse<T> {
  _FakeHttpResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatsApi extends _i1.Mock implements _i3.ChatsApi {
  MockChatsApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HttpResponse<_i5.ChatsResponse>> getChats() =>
      (super.noSuchMethod(
            Invocation.method(#getChats, []),
            returnValue: _i4.Future<_i2.HttpResponse<_i5.ChatsResponse>>.value(
              _FakeHttpResponse_0<_i5.ChatsResponse>(
                this,
                Invocation.method(#getChats, []),
              ),
            ),
          )
          as _i4.Future<_i2.HttpResponse<_i5.ChatsResponse>>);

  @override
  _i4.Future<_i2.HttpResponse<_i5.ChatResponse>> getChatWithId({
    required String? chatId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChatWithId, [], {#chatId: chatId}),
            returnValue: _i4.Future<_i2.HttpResponse<_i5.ChatResponse>>.value(
              _FakeHttpResponse_0<_i5.ChatResponse>(
                this,
                Invocation.method(#getChatWithId, [], {#chatId: chatId}),
              ),
            ),
          )
          as _i4.Future<_i2.HttpResponse<_i5.ChatResponse>>);

  @override
  _i4.Future<_i2.HttpResponse<_i5.ChatResponse>> getChatWithUser({
    required int? otherUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChatWithUser, [], {
              #otherUserId: otherUserId,
            }),
            returnValue: _i4.Future<_i2.HttpResponse<_i5.ChatResponse>>.value(
              _FakeHttpResponse_0<_i5.ChatResponse>(
                this,
                Invocation.method(#getChatWithUser, [], {
                  #otherUserId: otherUserId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.HttpResponse<_i5.ChatResponse>>);
}

/// A class which mocks [MessagesApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessagesApi extends _i1.Mock implements _i6.MessagesApi {
  MockMessagesApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HttpResponse<_i7.MessagesResponse>> getMessages({
    required int? chatId,
    required int? limit,
    required int? cursor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [], {
              #chatId: chatId,
              #limit: limit,
              #cursor: cursor,
            }),
            returnValue:
                _i4.Future<_i2.HttpResponse<_i7.MessagesResponse>>.value(
                  _FakeHttpResponse_0<_i7.MessagesResponse>(
                    this,
                    Invocation.method(#getMessages, [], {
                      #chatId: chatId,
                      #limit: limit,
                      #cursor: cursor,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.HttpResponse<_i7.MessagesResponse>>);
}
