// Mocks generated by Mockito 5.4.6 from annotations
// in kepleomax/test/mocks/mockito_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kepleomax/core/data/data_sources/chats_api_data_sources.dart'
    as _i2;
import 'package:kepleomax/core/data/data_sources/messages_api_data_sources.dart'
    as _i5;
import 'package:kepleomax/core/data/local_data_sources/chats_local_data_source.dart'
    as _i7;
import 'package:kepleomax/core/data/local_data_sources/users_local_data_source.dart'
    as _i8;
import 'package:kepleomax/core/models/user.dart' as _i11;
import 'package:kepleomax/core/network/apis/chats/chats_dtos.dart' as _i4;
import 'package:kepleomax/core/network/apis/messages/message_dtos.dart' as _i6;
import 'package:kepleomax/core/network/common/user_dto.dart' as _i9;
import 'package:kepleomax/core/network/websockets/models/online_status_update.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ChatsApiDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatsApiDataSource extends _i1.Mock
    implements _i2.ChatsApiDataSource {
  MockChatsApiDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Iterable<_i4.ChatDto>> getChats() =>
      (super.noSuchMethod(
            Invocation.method(#getChats, []),
            returnValue: _i3.Future<Iterable<_i4.ChatDto>>.value(
              <_i4.ChatDto>[],
            ),
          )
          as _i3.Future<Iterable<_i4.ChatDto>>);

  @override
  _i3.Future<_i4.ChatDto?> getChatWithId(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getChatWithId, [chatId]),
            returnValue: _i3.Future<_i4.ChatDto?>.value(),
          )
          as _i3.Future<_i4.ChatDto?>);

  @override
  _i3.Future<_i4.ChatDto?> getChatWithUser(int? otherUserId) =>
      (super.noSuchMethod(
            Invocation.method(#getChatWithUser, [otherUserId]),
            returnValue: _i3.Future<_i4.ChatDto?>.value(),
          )
          as _i3.Future<_i4.ChatDto?>);
}

/// A class which mocks [MessagesApiDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessagesApiDataSource extends _i1.Mock
    implements _i5.MessagesApiDataSource {
  MockMessagesApiDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.MessageDto>> getMessages({
    required int? chatId,
    required int? limit,
    int? cursor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [], {
              #chatId: chatId,
              #limit: limit,
              #cursor: cursor,
            }),
            returnValue: _i3.Future<List<_i6.MessageDto>>.value(
              <_i6.MessageDto>[],
            ),
          )
          as _i3.Future<List<_i6.MessageDto>>);
}

/// A class which mocks [ChatsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatsLocalDataSource extends _i1.Mock
    implements _i7.ChatsLocalDataSource {
  MockChatsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ChatDto>> getChats() =>
      (super.noSuchMethod(
            Invocation.method(#getChats, []),
            returnValue: _i3.Future<List<_i4.ChatDto>>.value(<_i4.ChatDto>[]),
          )
          as _i3.Future<List<_i4.ChatDto>>);

  @override
  _i3.Future<_i4.ChatDto?> getChat(int? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getChat, [chatId]),
            returnValue: _i3.Future<_i4.ChatDto?>.value(),
          )
          as _i3.Future<_i4.ChatDto?>);

  @override
  _i3.Future<_i4.ChatDto?> getChatByOtherUserId(int? otherUserId) =>
      (super.noSuchMethod(
            Invocation.method(#getChatByOtherUserId, [otherUserId]),
            returnValue: _i3.Future<_i4.ChatDto?>.value(),
          )
          as _i3.Future<_i4.ChatDto?>);

  @override
  _i3.Future<void> clearAndInsertChatsAndLastMessages(
    Iterable<_i4.ChatDto>? chats,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#clearAndInsertChatsAndLastMessages, [chats]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> insert(_i4.ChatDto? chat) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [chat]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> update(_i4.ChatDto? chat) =>
      (super.noSuchMethod(
            Invocation.method(#update, [chat]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteById(int? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteById, [chatId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> increaseUnreadCountBy1(int? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#increaseUnreadCountBy1, [chatId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> decreaseUnreadCount(int? chatId, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#decreaseUnreadCount, [chatId, amount]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [UsersLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsersLocalDataSource extends _i1.Mock
    implements _i8.UsersLocalDataSource {
  MockUsersLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> insert(_i9.UserDto? user) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> insertAll(Iterable<_i9.UserDto>? users) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [users]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateOnlineStatus(_i10.OnlineStatusUpdate? update) =>
      (super.noSuchMethod(
            Invocation.method(#updateOnlineStatus, [update]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setCurrentUser(_i11.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrentUser, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
